-- Migration 006: synthetic comparable listings for the Market Analyst (architecture doc §9.1).
-- Every row is generated by listing_assistant.synthetic_market; is_synthetic must be 1.

CREATE TABLE comparable_listings (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    make          TEXT NOT NULL,
    model         TEXT NOT NULL,
    model_year    INTEGER NOT NULL,
    mileage_km    INTEGER NOT NULL CHECK (mileage_km >= 0),
    city          TEXT NOT NULL,
    price_try     INTEGER NOT NULL CHECK (price_try > 0),
    description   TEXT NOT NULL,
    is_synthetic  INTEGER NOT NULL CHECK (is_synthetic = 1)
);
CREATE INDEX idx_comparables_lookup ON comparable_listings (make, model, model_year);

PRAGMA user_version = 6;
